name: image_client
description: "A new Flutter project."
publish_to: 'none' 
version: 1.0.0+1
environment:
  sdk: ^3.12.2
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
flutter:
  uses-material-design: true
  # TODO #1a : Toutes les images utilisées comme asset doivent être déclarées ici
  assets:
    - assets/images/anse-aux-gascons.jpeg
  # - assets fonctionnerait aussi  
